parameters:
    smartcore.validation.validator.class: Smartbox\CoreBundle\Validation\ValidatorWithExclusion
    smartcore.serialization.subscriber.class: Smartbox\CoreBundle\Serializer\Handler\SerializerEventsSubscriber
    smartcore.hydrator.group_version.class: Smartbox\CoreBundle\Hydrator\GroupVersionHydrator
    smartcore.deserialization_casting_checker.class: Smartbox\CoreBundle\Serializer\StrongDeserializationCastingChecker
    smartcore.deserialization_types_validator.class: Smartbox\CoreBundle\Serializer\DeserializationTypesValidator
    smartcore.xml_deserialization_visitor.class: Smartbox\CoreBundle\Serializer\XmlDeserializationVisitor
    smartcore.json_deserialization_visitor.class: Smartbox\CoreBundle\Serializer\JsonDeserializationVisitor
    smartcore.array_serialization_visitor.class: Smartbox\CoreBundle\Serializer\ArraySerializationVisitor
    smartcore.array_deserialization_visitor.class: Smartbox\CoreBundle\Serializer\ArrayDeserializationVisitor

    smartcore.monolog.formatter.json.class: Smartbox\CoreBundle\Utils\Monolog\Formatter\JMSSerializerFormatter

    smartcore.generator.random_fixture.class: Smartbox\CoreBundle\Utils\Generator\RandomFixtureGenerator
    smartcore.helper.namespace_resolver.class: Smartbox\CoreBundle\Utils\Helper\NamespaceResolver

    # OVERRIDING JMS
    jms_serializer.metadata.annotation_driver.class: Smartbox\CoreBundle\Serializer\Metadata\Driver\AnnotationDriver
    jms_serializer.array_collection_handler.class: Smartbox\CoreBundle\Serializer\Handler\DateHandler

services:
    smartcore.serialization.subscriber:
        class:  '%smartcore.serialization.subscriber.class%'
        tags:
            - { name: jms_serializer.event_subscriber }

    smartcore.validation.validator:
        class: '%smartcore.validation.validator.class%'
        decorates: validator
        calls:
            - [ setDecoratedValidator, ['@smartcore.validation.validator.inner'] ]
            - [ setMetadataFactory, ['@jms_serializer.metadata_factory'] ]

    smartcore.hydrator.group_version:
        class: '%smartcore.hydrator.group_version.class%'
        arguments: ['@jms_serializer.metadata_factory']

    smartcore.deserialization_casting_checker:
        class: '%smartcore.deserialization_casting_checker.class%'

    smartcore.deserialization_types_validator:
        class: '%smartcore.deserialization_types_validator.class%'
        arguments: ['@smartcore.deserialization_casting_checker']

    smartcore.xml_deserialization_visitor:
        class: '%smartcore.xml_deserialization_visitor.class%'
        arguments:
          - '@jms_serializer.naming_strategy'
          - '@jms_serializer.object_constructor'
          - '@smartcore.deserialization_types_validator'
        calls:
          - [setDoctypeWhitelist, ['%jms_serializer.xml_deserialization_visitor.doctype_whitelist%']]
        tags:
            - { name: jms_serializer.deserialization_visitor, format: xml }

    smartcore.json_deserialization_visitor:
        class: '%smartcore.json_deserialization_visitor.class%'
        arguments:
          - '@jms_serializer.naming_strategy'
          - '@jms_serializer.object_constructor'
          - '@smartcore.deserialization_types_validator'
        tags:
            - { name: jms_serializer.deserialization_visitor, format: json }

    smartcore.array_deserialization_visitor:
        class: '%smartcore.array_deserialization_visitor.class%'
        arguments:
            - '@jms_serializer.naming_strategy'
            - '@jms_serializer.object_constructor'
            - '@smartcore.deserialization_types_validator'
        tags:
            - { name: jms_serializer.deserialization_visitor, format: array }

    smartcore.array_serialization_visitor:
        class: '%smartcore.array_serialization_visitor.class%'
        arguments: ['@jms_serializer.naming_strategy']
        tags:
            - { name: jms_serializer.serialization_visitor, format: array }

    smartcore.array_deserialization_visitor_mongo:
        class: '%smartcore.array_deserialization_visitor.class%'
        arguments:
            - '@jms_serializer.naming_strategy'
            - '@jms_serializer.object_constructor'
            - '@smartcore.deserialization_types_validator'
        tags:
            - { name: jms_serializer.deserialization_visitor, format: mongo_array }

    smartcore.array_serialization_visitor_mongo:
        class: '%smartcore.array_serialization_visitor.class%'
        arguments: ['@jms_serializer.naming_strategy']
        tags:
            - { name: jms_serializer.serialization_visitor, format: mongo_array }

    smartcore.monolog.formatter.json:
        class: '%smartcore.monolog.formatter.json.class%'
        calls:
            - [setSerializer, ['@jms_serializer']]

    smartcore.helper.entity_namespace_resolver:
        class: '%smartcore.helper.namespace_resolver.class%'
        arguments: ['%smartcore.entity.namespaces%']

    smartcore.generator.random_fixture:
        class: '%smartcore.generator.random_fixture.class%'
        arguments: ['@jms_serializer.metadata_factory', '@smartcore.helper.entity_namespace_resolver']

    ## SMOKE TESTS ##
    # COMMAND
    smartcore.command.smoke_test:
        class: Smartbox\CoreBundle\Command\SmokeTestRunCommand
        tags:
            -  { name: console.command }

    smartbox_core.command_fixtures.generate_random_fixture_command:
        class: Smartbox\CoreBundle\Command\Fixtures\GenerateRandomFixtureCommand
        arguments:
            - 'smartbox:core:generate:random-fixture'
            - '@jms_serializer'
            - '@smartcore.helper.entity_namespace_resolver'
            - '@smartcore.generator.random_fixture'
        tags:
            - { name: console.command }